sudo: required


services:
  - docker

jobs:
  include:
    - stage: "Docker 1"
    - language: bash
    - name:  "Docker compose up"
    - script: docker-compose up



    - stage: "Docker 2"
    - language: bash
    - name:  "Docker list processes"
    - script: docker ps -a
