sudo: required

language: php

services:
  - docker

jobs:
  include:
    - stage: "Docker"
    - name:  "Docker compose up"
    - script: docker-compose up
  include:
    - stage: "Docker"
    - name:  "Docker list processes"
    - script: docker ps -a
