sudo: true

language: bash

services:
  - docker

before_script:
- if [[ $TRAVIS_BRANCH == "master" ]]; then export APP_ENV=APP_ENV_PRODUCTION; fi
- if [[ $TRAVIS_BRANCH =~ (^release) ]]; then export APP_ENV=APP_ENV_STAGING; fi


jobs:
  include:
    - stage: "Docker 1"
    - name:  "Docker compose up"



    - stage: "Docker 2"
    - name:  "Docker list processes"
    - script: docker ps -a
