sudo: required

language: bash

services:
  - docker

jobs:
  include:
    - stage: "Docker 1"
    - name:  "Docker compose up"
    - script: sudo docker-compose up



    - stage: "Docker 2"
    - name:  "Docker list processes"
    - script: docker ps -a
