sudo: true

language: bash

services:
  - docker

before_script:
- if [[ $TRAVIS_BRANCH == "master" ]]; then export APP_ENV=$APP_ENV_PRODUCTION; fi
- if [[ $TRAVIS_BRANCH =~ (^release) ]]; then export APP_ENV=$APP_ENV_STAGING; fi

jobs:
  include:

    - stage: "Docker: build and run containers"
    - script: docker-compose up -d

    - stage: "Docker: list processes"
    - script: docker ps -a

    - stage: "Run tests"
    - script: docker-compose exec cicd_php vendor/phpunit/phpunit/phpunit
