sudo: true

language: bash

services:
  - docker

before_install:
  - docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD

before_script:
  - if [[ $TRAVIS_BRANCH == "master" ]]; then export APP_ENV=$APP_ENV_PRODUCTION; fi
  - if [[ $TRAVIS_BRANCH =~ (^release) ]]; then export APP_ENV=$APP_ENV_STAGING; fi

jobs:
  include:
    - stage: "Docker: Running Tests"
      script:
        - docker network create sites_default
        - docker-compose up -d
        - docker-compose exec php composer install
        - docker-compose exec php ./vendor/bin/phpunit
