version: '3'
services:
  web:
    container_name: nginx
    build: .docker/nginx
    image: nginx
    environment:
      VIRTUAL_HOST: hello.wtf
      VIRTUAL_PORT: 80
    volumes:
        -  .:${APP_DIRECTORY}
  php:
    container_name: php
    build: .docker/php
    image: roykesserwani/cicd:${TAG}
    volumes:
        - .:${APP_DIRECTORY}
    environment:
        APP_ENV: ${APP_ENV}
        APP_KEY: ${APP_KEY}

networks:
  default:
    external:
      name: sites_default